---

- name: Provision Sharepear
  hosts: all
  sudo: yes
  vars_files:
    - vars/apache.yml
    - vars/apt.yml
    - vars/common.yml # variable use in another vars file
    - vars/fail2ban.yml
    - vars/iptables.yml
    - vars/mysql.yml
    - vars/php.yml
    - vars/ssh.yml
  roles:
    - { role: kosssi.apt, tags: apt }
    - { role: Stouts.iptables, tags: iptables }
    - { role: nickjj.fail2ban, tags: fail2ban }
    - { role: kosssi.ssh, tags: ssh }
    - { role: kosssi.php, tags: php }
    - { role: kosssi.composer, tags: composer }
    - { role: kosssi.apache, tags: apache }
    - { role: Ansibles.mysql, tags: mysql }
