---

- name: Provision Sharepear
  hosts: all
  sudo: yes
  vars_files:
    - vars/common.yml
    - vars/apt.yml
    - vars/fail2ban.yml
    - vars/iptables.yml
    - vars/php.yml
    - vars/ssh.yml
  roles:
    - { role: kosssi.apt, tags: apt }
    - { role: Stouts.iptables, tags: iptables }
    - { role: nickjj.fail2ban, tags: fail2ban }
    - { role: kosssi.ssh, tags: ssh }
    - { role: kosssi.php, tags: php }
