---

- name: Add .profile for www-data.
  command:
    cp /home/"{{ user_root }}"/.profile /var/www/.profile creates=/var/www/.profile

- name: Set correct permissions
  file:
    path="{{ item.path }}"
    owner="{{ item.owner }}"
    group="{{ item.group }}"
    mode="{{ item.mode }}"
    state="{{ item.state }}"
  with_items:
      - { path: '/var/www', owner: 'www-data', group: 'www-data', mode: '0755', state: 'directory' }
      - { path: '/var/www/.ssh', owner: 'www-data', group: 'www-data', mode: '0700', state: 'directory' }
      - { path: '/var/www/.profile', owner: 'www-data', group: 'www-data', mode: '0700', state: 'file' }
